# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: project ci/cd pipeline 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15 #build runtime limit.

    steps:
    - uses: actions/checkout@v3
    #install the programming language java
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    #install the dependencies
    - name: Build with Maven
      run: mvn -B package --file pom.xml



    #validate the quality of the code using pmd
    #- name: Run PMD
      #uses: pmd/pmd-action@v2.0.0
      #with:
        #version: '6.36.0'
        #target-directory: src/main/java
        #rule-sets: java-basic,java-design






    - name: Run tests
      run: mvn test




    #send notification to mail about the state of my build
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'App build status'
        to: 'hananetest9@example.com'
        body: 'The app build has completed.'